bookingsite/booking/urls.py
from django.urls import path
from . import views

from .filters import OfferFilter

app_name = 'booking'
urlpatterns = [
    path('', views.IndexFilterView.as_view(filterset_class=OfferFilter), name='index'),
    path('offers/<slug:slug>/', views.OfferDetailView.as_view(), name='detail'),
    path('offers/<slug:slug>/book', views.CreateBookingView.as_view(), name='book'),
    path('sign_in/', views.LoginUser.as_view(), name='sign_in'),
    path('sign_up/', views.RegisterUser.as_view(), name='sign_up'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('bookings/<int:pk>/delete', views.delete_booking_view, name='delete_booking')
]

bookingsite/bookingsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings



urlpatterns = [
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookingsite/booking/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone

class Offer(models.Model):

    LODGING_TYPES = (
        ('F', 'Flat'),
        ('HST', 'Hostel'),
        ('HS', 'House'),
        ('HR', 'Hotel Room')
    )
    PLACES_NUMBERS = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5)
    )

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField(max_length=5000)

    image = models.ImageField(upload_to='photo/%Y/%m/%d/')

    lodging_type = models.CharField(max_length=3, choices=LODGING_TYPES, default='HR')
    places = models.IntegerField(default=1, choices=PLACES_NUMBERS)
    night_price = models.PositiveIntegerField(default=100, validators=[MinValueValidator(1), MaxValueValidator(100)], verbose_name='Night price')

    isWifi = models.BooleanField(default=True, verbose_name='WiFi')
    isConditioner = models.BooleanField(default=False, verbose_name='Conditioner')
    isKitchen = models.BooleanField(default=False, verbose_name='Kitchen')
    isBreakfast = models.BooleanField(default=False, verbose_name='Breakfast')

    date_created = models.DateField(auto_now_add=True)

    isPublished = models.BooleanField(default=True, verbose_name='Published')

    # добавить метод get_absolute_url()
    # сортировку сделать и фильтрацию
    # добавить комментарии (один пользователь = много комментариев)
    # добавить систему рейтинга (один пользователь = одна оценка)
    # rating = models.FloatField(default=0, editable=False)
    # total_rates = models.PositiveIntegerField(default=1, editable=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('booking:detail', kwargs={'slug':self.slug,})

class Booking(models.Model):

    PAYMENT_METHOD = (
        ('Cash', 'Cash'),
        ('Cart', 'Cart')
    )

    BOOKING_STATES = (
        ('P', 'In processing'),
        ('A', 'Accepted'),
        ('R', 'Rejected')

    )

    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name='requests')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings')

    payment_method = models.CharField(max_length=4,choices=PAYMENT_METHOD, default='Cash')

    arrival_date = models.DateField()
    departure_date = models.DateField()

    state = models.CharField(max_length=1, choices=BOOKING_STATES, default='P')

    def get_duration(self):
        pass

    def get_total_price(self):
        return (self.departure_date - self.arrival_date).days * self.offer.night_price

    def is_past_due(self):
        return timezone.now().date() >= self.arrival_date

    def __str__(self):
        return str(self.pk) + ' ' + self.offer.name

bookingsite/booking/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError

from .models import *
import datetime

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class BookingForm (forms.ModelForm):

    def clean_arrival_date(self):
        self.arrival_date = self.cleaned_data['arrival_date']
        if self.arrival_date <= datetime.date.today():
            raise ValidationError('You can`t create booking in past')
        return self.arrival_date

    def clean_departure_date(self):
        departure_date = self.cleaned_data['departure_date']
        if departure_date <= self.arrival_date:
            raise ValidationError('Departure date can`t be less than arrival date')
        return departure_date

    class Meta:
        model = Booking
        fields = '__all__'

bookingsite/booking/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import  HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from .forms import *
from .models import *
from .utils import DataMixin
from .filters import *
from django_filters.views import FilterView


class IndexFilterView(DataMixin, FilterView):
        template_name = 'booking/index.html'
        context_object_name = 'offers'
        paginate_by = 2

        def get_queryset(self):
            return Offer.objects.filter(isPublished=True).order_by('-date_created')

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            c_def = self.get_user_context(title='Booking service')
            context = dict(list(context.items()) + list(c_def.items()))
            return context

class CreateBookingView(LoginRequiredMixin, DataMixin,  generic.DetailView):
    model = Offer
    template_name = 'booking/book.html'
    login_url = 'booking:sign_in'

    def get_queryset(self):
        return Offer.objects.filter(isPublished=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Book: ' + self.object.name
        form = BookingForm()
        c_def = self.get_user_context(title=title, form=form)
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def post(self,request,slug):
        # request.POST['offer'] = self.object.pk
        post = request.POST.copy()
        post['user'] = request.user.pk
        post['state'] = Booking.BOOKING_STATES[0][0]
        request.POST = post
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('booking:profile')
        return redirect(request.META['HTTP_REFERER'])

class OfferDetailView(DataMixin, generic.DetailView):
    model = Offer
    template_name = 'booking/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=self.object.name)
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def get_queryset(self):
        return Offer.objects.filter(isPublished=True)


class RegisterUser(DataMixin, generic.CreateView):
    form_class = RegisterUserForm
    template_name = 'booking/user-auth.html'
    success_url = reverse_lazy('booking:sign_in')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('booking:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Sign up'
        c_def = self.get_user_context(title=title, menu_item_selected=title)
        context = dict(list(context.items()) + list(c_def.items()))
        return context

class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'booking/user-auth.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Sign in'
        c_def = self.get_user_context(title=title, menu_item_selected= title)
        context = dict(list(context.items()) + list(c_def.items()))
        return context




def logout_view(request):
    logout(request)
    return redirect('booking:index')

def delete_booking_view(request, pk):
    if request.user.is_authenticated:
        booking = Booking.objects.get(pk=pk)
        if booking and booking.user.pk is request.user.pk:
            if booking.state == Booking.BOOKING_STATES[0][0] and not booking.is_past_due():
                booking.delete()
    return redirect('booking:profile')

class ProfileView (LoginRequiredMixin,DataMixin, generic.ListView):
    login_url = 'booking:sign_in'
    template_name = 'booking/profile.html'
    context_object_name = 'bookings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Profile'
        c_def = self.get_user_context(title=title, menu_item_selected=title)
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def get_queryset(self):
        return Booking.objects.filter(user__pk=self.request.user.pk).order_by('-pk')

bookingsite/booking/templates/booking/book.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
<div class="book-content-main-block">
<div class="form-block">
  <div class="form-block-header">
    <p class="form-block-header-text">Make booking</p>
  </div>
  <div class="form-contains-block">

    <form method="post">
  {% csrf_token %}
    <input type="hidden" readonly name="offer" required value="{{ object.pk}}" id="id_offer">


      <div class="form-field"><label class="form-label" for="id_arrival_date">Arrival date:</label> <input class="form-input" type="date" name="arrival_date" required id="id_arrival_date"></div>
      <div class="form-error">{{ arrival_date.errors }}</div>

        <div class="form-field"><label class="form-label" for="id_departure_date">Departure date:</label> <input type="date" class="form-input" name="departure_date" required id="id_departure_date"></div>
      <div class="form-error">{{ arrival_date.errors }}</div>

      <div class="form-field"><label class="form-label" for="id_payment_method">Payment method:</label>
          <select class="form-input form-combobox" id="book-payment-method-combobox" name="payment_method" id="id_payment_method">
            <option value="Cash" selected>Cash</option>

            <option value="Cart">Cart</option>
          </select>
      </div>

      <div class="form-non-field-error">{{ form.non_field_errors }}</div>

        <div class="book-offer-block">
        <div class="book-offer-paragraph"><b>Name:</b> {{ object.name |truncatechars:40 }}</div>
        <div class="book-offer-paragraph"><b>Type:</b>  {{ object.get_lodging_type_display }}</div>
          <div class="book-offer-paragraph"><b>Per night price:</b>  {{ object.night_price }} USD</div>
          <div class="book-offer-paragraph"><b>Places:</b>  {{ object.places }}</div>
          <div class="book-offer-paragraph"><b>Services:</b>  Air conditioner ({%if object.isConditioner %}+{% else %}-{% endif %}), Wifi ({%if object.isWifi %}+{% else %}-{% endif %}), Kitchen ({%if object.isKitchen %}+{% else %}-{% endif %}), Breakfast ({%if object.isBreakfast %}+{% else %}-{% endif %})</div>
        </div>

      <div class="form-block-submit-button-block">
      <button class="form-block-submit-button" type="submit">Book</button>
      </div>

    </form>

  </div>
</div>

</div>


{% endblock content %}

bookingsite/booking/templates/booking/detail.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
    <div class="details-content-block">

        <div class="offer-detail-block offer-detail-header">
            <p class="offer-detail-header-text">{{object.name}}</p>
        </div>

        <div class="offer-image">
                <img src="{% get_media_prefix %}{{ object.image }}" class="offer-thumbnailimage offer-detail-image">
                <p class="offer-onimage" id="offer-detail-onimage-text">{{ object.get_lodging_type_display}}</p>
                <div class="offer-onimage" id="offer-detail-onimage-persons">
                    {% with ''|center:object.places as range %}
                    {% for _ in range %}
                    <img src="{% static 'booking/images/man_figure.svg' %}" class="offer-man-figure-image">
                    {% endfor %}
                    {% endwith %}
                </div>
                    {% if object.isKitchen or object.isConditioner or object.isBreakfast or object.isWifi %}
                        <div class="offer-onimage offer-detail-onimage-services">

                            <div class="offer-services-block">
                            <div class="offer-service-spacer"></div>
                            {%if object.isKitchen%}
                                <img class="service-thumbnailimage" title='Kitchen' src="{% static 'booking/images/fork-spoon.svg' %}">
                                <div class="offer-service-spacer"></div>
                            {% endif %}
                            {%if object.isConditioner%}
                                <img class="service-thumbnailimage" title='Conditioner' src="{% static 'booking/images/air-conditioner.svg' %}">
                                 <div class="offer-service-spacer"></div>
                            {% endif %}
                            {%if object.isBreakfast%}
                                <img class="service-thumbnailimage" title='Breakfast' src="{% static 'booking/images/mug.svg' %}">
                                 <div class="offer-service-spacer"></div>
                            {% endif %}
                            {%if object.isWifi%}
                                <img class="service-thumbnailimage" title='Wi-Fi' src="{% static 'booking/images/wifi.svg' %}">
                                 <div class="offer-service-spacer"></div>
                            {% endif %}
                            </div>

                        </div>
                    {% endif %}
                <div class="offer-onimage offer-detail-onimage-book-block">
                    <div class="offer-details-price-info-block">
                    <p class="offer-price-caption black-text">{{object.night_price}} $</p>
                    <p class="offer-price-additional-text-block black-text">(per night)</p>
                </div>
                    <a class="offer-detail-book-button" href="{% url 'booking:book' object.slug %}">Book now</a>
                </div>
            </div>

        <div class="offer-detail-block">
            <div class="offer-detail-description-header">
                <p class="offer-detail-header-text">Description</p>
            </div>
            <div class="offer-detail-description-block">
                <div class="offer-detail-description-text">{{object.description|linebreaks}}</div>
            </div>
        </div>

    </div>
{% endblock content %}

bookingsite/booking/templates/booking/index.html
{% extends 'booking/base.html' %}
{% load static %}
{% load booking_extras %}

{% block content %}
{% if offers %}
<div class="search-block">

    <div class="form-block" id="filter-form-block">
  <div class="form-block-header" id="filter-form-block-header">
    <p class="form-block-header-text">Filter</p>
  </div>
  <div class="form-contains-block">

    <form method="get">
        {% csrf_token %}
<div class="form-field filter-form-field"><label class="filter-form-label" for="name_input">Name:</label><input class="form-input filter-form-input" type="text" name="name" id="name_input" value="{{request.GET.name}}"></div>

 <div class="form-field filter-form-field"><label class="filter-form-label" for="id_night_price_0">Price:</label>
     <div class="form-two-fields-in-row"><input class="form-input filter-form-input filter-form-input-number-field" type="number" name="night_price_min" id="id_night_price_0" placeholder="min" min="0" value="{{request.GET.night_price_min}}">

<input class="form-input filter-form-input filter-form-input-number-field" type="number" name="night_price_max" id="id_night_price_1" placeholder="max" min="0" value="{{request.GET.night_price_max}}">
         </div>

 </div>

        <div class="filter-table-block">
                <div class="filter-service-header">
                    <p class="filter-service-header-text filter-service-header-text-main-column">Service</p>
                    <p class="filter-service-header-text filter-service-header-text-radiobutton-column">-</p>
                    <p class="filter-service-header-text filter-service-header-text-radiobutton-column">Yes</p>
                    <p class="filter-service-header-text filter-service-header-text-radiobutton-column">No</p>
                </div>

                <div class="filter-service-row">
                    <img class="service-thumbnailimage filter-service-thumbnailimage" title='Kitchen' src="{% static 'booking/images/fork-spoon.svg' %}">
                    <div class="filter-service-radiobuttons-group">
                        <input class="filter-radiobutton" name='isKitchen' value="unknown" type="radio" {% if request.GET.isKitchen == 'unknown' or not request.GET.isKitchen %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isKitchen' value="true" type="radio" {% if request.GET.isKitchen == 'true' %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isKitchen' value="false" type="radio" {% if request.GET.isKitchen == 'false' %} checked="checked" {% endif %}>
                    </div>

                </div>

                <div class="filter-service-row alternative-filter-service-row">
                    <img class="service-thumbnailimage filter-service-thumbnailimage" title='Conditioner' src="{% static 'booking/images/air-conditioner.svg' %}">
                    <div class="filter-service-radiobuttons-group">
                        <input class="filter-radiobutton" name='isConditioner' value="unknown" type="radio" {% if request.GET.isConditioner == 'unknown' or not request.GET.isConditioner %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isConditioner' value="true" type="radio" {% if request.GET.isConditioner == 'true' %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isConditioner' value="false" type="radio" {% if request.GET.isConditioner == 'false' %} checked="checked" {% endif %}>
                    </div>

                </div>

                <div class="filter-service-row">
                    <img class="service-thumbnailimage filter-service-thumbnailimage" title='Breakfast' src="{% static 'booking/images/mug.svg' %}">
                    <div class="filter-service-radiobuttons-group">
                        <input class="filter-radiobutton" name='isBreakfast' value="unknown" type="radio" {% if request.GET.isBreakfast == 'unknown' or not request.GET.isBreakfast %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isBreakfast' value="true" type="radio" {% if request.GET.isBreakfast == 'true' %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isBreakfast' value="false" type="radio" {% if request.GET.isBreakfast == 'false' %} checked="checked" {% endif %}>
                    </div>

                </div>

                <div class="filter-service-row alternative-filter-service-row" id="filter-service-last-row">
                    <img class="service-thumbnailimage filter-service-thumbnailimage" title='Wi-Fi' src="{% static 'booking/images/wifi.svg' %}">
                    <div class="filter-service-radiobuttons-group">
                        <input class="filter-radiobutton" name='isWifi' value="unknown" type="radio" {% if request.GET.isWifi == 'unknown' or not request.GET.isWifi %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isWifi' value="true" type="radio" {% if request.GET.isWifi == 'true' %} checked="checked" {% endif %}>
                        <input class="filter-radiobutton" name='isWifi' value="false" type="radio" {% if request.GET.isWifi == 'false' %} checked="checked" {% endif %}>
                    </div>

                </div>



            </div>


        <div class="filter-table-block">
            <div class="filter-lodging-type-block">
            <div class="filter-lodging-type-header">
                <p id="filter-lodging-type-header-text">Lodging Type</p>
            </div>

            <div class="filter-lodging-type-content-block">

                <div class="filter-lodging-type-content-half">
                    <div class="filter-lodging-type-check-box-block">
                        <input class="filter-lodging-type-check-box" type="checkbox" name="lodging_type" value="F" id="flat_cb" {% if 'F' in request.GET|get_list:'lodging_type'%} checked="checked" {% endif %}>
                        <label class="filter-form-label" for="flat_cb">Flat</label>
                    </div>
                    <div class="filter-lodging-type-spacer"></div>
                    <div class="filter-lodging-type-check-box-block">
                        <input class="filter-lodging-type-check-box" type="checkbox" name="lodging_type" value="HST" id="hostel_cb" {% if 'HST' in request.GET|get_list:'lodging_type'%} checked="checked" {% endif %}><label class="filter-form-label" for="hostel_cb">Hostel</label>
                    </div>
                </div>

                <div class="filter-lodging-type-content-half">
                    <div class="filter-lodging-type-check-box-block">
                        <input class="filter-lodging-type-check-box" type="checkbox" name="lodging_type" value="HS" id="house_cb" {% if 'HS' in request.GET|get_list:'lodging_type'%} checked="checked" {% endif %}><label class="filter-form-label" for="house_cb">House</label>
                    </div>
                    <div class="filter-lodging-type-spacer"></div>
                    <div class="filter-lodging-type-check-box-block">
                        <input class="filter-lodging-type-check-box" type="checkbox" name="lodging_type" value="HR" id="hotel_room_cb" {% if 'HR' in request.GET|get_list:'lodging_type'%} checked="checked" {% endif %}><label class="filter-form-label" for="hotel_room_cb">Hotel room</label>
                    </div>

                </div>
            </div>


        </div>
        </div>


    <div id="filter-after-table-spacer"></div>
    <div class="form-field filter-form-field">
        <label class="filter-form-label" for="id_places">Places:</label>
        <select class="form-input filter-form-input form-combobox" name="places" id="id_places">
      <option value="" {% if request.GET.places == '' or not request.GET.places %} selected = "selected"{% endif %} >No matter</option>

      <option value="1" {% if request.GET.places == '1' %} selected = "selected"{% endif %} >1</option>

      <option value="2" {% if request.GET.places == '2' %} selected = "selected"{% endif %} >2</option>

      <option value="3" {% if request.GET.places == '3' %} selected = "selected"{% endif %} >3</option>

      <option value="4" {% if request.GET.places == '4' %} selected = "selected"{% endif %} >4</option>

      <option value="5" {% if request.GET.places == '5' %} selected = "selected"{% endif %} >5</option>

    </select>
    </div>

    <div class="form-field filter-form-field">
        <label class="filter-form-label" for="id_o">Ordering:</label>
        <select class="form-input filter-form-input form-combobox" name="o" id="id_o">

            <option value="-date_created" {% if request.GET.o == '-date_created' or not request.GET.o %} selected = "selected"{% endif %} >Date (DESC)</option>
            <option value="date_created" {% if request.GET.o == 'date_created'%} selected = "selected"{% endif %} >Date (ASC)</option>
            <option value="-night_price" {% if request.GET.o == '-night_price' %} selected = "selected"{% endif %} >Price (DESC)</option>
            <option value="night_price" {% if request.GET.o == 'night_price' %} selected = "selected"{% endif %} >Price (ASC)</option>



    </select>
    </div>

      <div class="form-non-field-error"></div>

      <div class="form-block-submit-button-block">
      <button class="form-block-submit-button" type="submit">Search</button>
      </div>
    </form>
  </div>

</div>
</div>
<div class="results-list">

    {% for o in offers %}
        <div class="offer-block">
            <div class="offer-block-header">
                <p class="offer-caption">{{o.name |truncatechars:40}}</p>
                <div class="offer-price-info">
                    <p class="offer-price-caption">{{o.night_price}} $</p>
                    <p class="offer-price-additional-text-block">(per night)</p>
                </div>
            </div>

                {% if o.image %}
            <div class="offer-image">
                <img src="{% get_media_prefix %}{{ o.image }}" class="offer-thumbnailimage">
                <p class="offer-onimage" id="offer-onimage-text">{{ o.get_lodging_type_display}}</p>
                <div class="offer-onimage" id="offer-onimage-persons">
                    {% with ''|center:o.places as range %}
                    {% for _ in range %}
                    <img src="{% static 'booking/images/man_figure.svg' %}" class="offer-man-figure-image">
                    {% endfor %}
                    {% endwith %}
                </div>
            </div>

                {% endif %}

                <div class="offer-block-bottom-ribbon">
                    {% if o.isKitchen or o.isConditioner or o.isBreakfast or o.isWifi %}
                    <div class="offer-services-block">
                         <div class="offer-service-spacer"></div>
                    {%if o.isKitchen%}
                        <img class="service-thumbnailimage" title='Kitchen' src="{% static 'booking/images/fork-spoon.svg' %}">
                        <div class="offer-service-spacer"></div>
                    {% endif %}
                    {%if o.isConditioner%}
                        <img class="service-thumbnailimage" title='Conditioner' src="{% static 'booking/images/air-conditioner.svg' %}">
                         <div class="offer-service-spacer"></div>
                    {% endif %}
                    {%if o.isBreakfast%}
                        <img class="service-thumbnailimage" title='Breakfast' src="{% static 'booking/images/mug.svg' %}">
                         <div class="offer-service-spacer"></div>
                    {% endif %}
                    {%if o.isWifi%}
                        <img class="service-thumbnailimage" title='Wi-Fi' src="{% static 'booking/images/wifi.svg' %}">
                         <div class="offer-service-spacer"></div>
                    {% endif %}
                    </div>
                    {% endif %}
                    <div class="offer-buttons">
                        <a class="offer-button" id="book-button" href="{% url 'booking:book' o.slug %}">Book</a>
                        <div class="offer-button-spacer"></div>
                        <a class="offer-button" id="details-button" href="{{o.get_absolute_url}}">Details</a>
                    </div>
                    </div>

                </div>
        {% endfor %}

        {% if page_obj.has_other_pages %}
            <div class="page-navigation-block">
                {% if page_obj.has_previous %}
                    <a class="page-index-block page-index-block-unselected page-index-more-margin" href="{% if request.GET %}?{{ request.GET.urlencode }}&{% else %}?{% endif%}page=1">&laquo;</a>
                {% endif %}
                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <div class="page-index-block page-index-block-selected"> {{ p }} </div>
                    {% elif page_obj.number|add:2 >= p or page_obj.number|add:-2 <= p %}
                        <a class="page-index-block page-index-block-unselected" href="{% if request.GET %}?{{ request.GET.urlencode }}&{% else %}?{% endif%}page={{ p }}"> {{ p }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="page-index-block page-index-block-unselected page-index-more-margin" href="{% if request.GET %}?{{ request.GET.urlencode }}&{% else %}?{% endif%}page={{ paginator.num_pages }}">&raquo;</a>
                {% endif %}
            </div>
        {% endif%}

            </div>
{% else %}
    <div class="profile-welcome-header lighter-blue-header">No offers currently available:)</div>
{% endif %}

{% endblock content %}

bookingsite/booking/templates/booking/profile.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
<div class="profile-content-block">
    <div class="profile-welcome-header">Welcome, {{ request.user.username }}</div>
    {% if bookings %}
    <div class="profile-welcome-header lighter-blue-header">There are your bookings</div>
    <table id="bookings-table">
        <tr>
            <th>№</th>
            <th>Name</th>
            <th>Type</th>
            <th>Arrival</th>
            <th>Departure</th>
            <th>Total price</th>
            <th>Status</th>
        </tr>
        {% for booking in bookings %}
          <tr>
            <td>{{ booking.pk }}</td>
              <td><a class="link-offer" href="{{ booking.offer.get_absolute_url }}">{{ booking.offer.name |truncatechars:40 }}</a></td>
            <td>{{ booking.offer.get_lodging_type_display }}</td>
            <td>{{ booking.arrival_date  }}</td>
            <td>{{ booking.departure_date }}</td>
            <td>{{ booking.get_total_price }} $</td>
            <td>
                {% if booking.state == 'P' %}<div class="proccessing-text-style"> {{ booking.get_state_display }} </div>
              {% elif booking.state == 'A' %} <div class="accepted-text-style"> {{ booking.get_state_display }} </div>
              {% elif booking.state == 'R' %} <div class="rejected-text-style"> {{ booking.get_state_display }} </div>
              {% endif %}
            </td>
              {% if not booking.is_past_due and booking.state == 'P' %}
              <td><a class="link-delete" href="{% url 'booking:delete_booking' booking.pk%}">Delete</a></td>
              {% endif %}
          </tr>
        {% endfor%}
    </table>
    {% else %}
    <div class="profile-welcome-header lighter-blue-header">You don`t have bookings yet:)</div>
    {% endif %}
</div>




{% endblock content %}